EXPERIEMENT NO. 10

CREATE DATASET AND LOAD DATASET

NAME- DOLLY DALAL  
PRN- 25070123044  
BATCH- ENTC A2

In [46]:
#dataset creation
import pandas as pd
data={
    "roll_no":[101,102,103,104,105],
    "gender":["female","male","male","female","male"],
    "CGPA":[8.2,7.6,4.9,9.1,7.2,],
    "department":["CSE","EEE","ENTC","MECHANICAL","CSE"],
    "Year":[1,2,3,4,2]
}
df=pd.DataFrame(data)
df.to_csv("student_data.csv",index=False)
df

   roll_no  gender  CGPA  department  Year
0      101  female   8.2         CSE     1
1      102    male   7.6         EEE     2
2      103    male   4.9        ENTC     3
3      104  female   9.1  MECHANICAL     4
4      105    male   7.2         CSE     2

In [47]:
df.shape

(5, 5)

In [48]:
df.size

25

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   roll_no     5 non-null      int64
 1   gender      5 non-null      object
 2   CGPA        5 non-null      float64
 3   department  5 non-null      object
 4   Year        5 non-null      int64
dtypes: float64(1), int64(2), object(2)
memory usage: 332.0+ bytes

In [50]:
df.describe()

          roll_no      CGPA      Year
count    5.000000  5.000000  5.000000
mean   103.000000  7.400000  2.400000
std      1.581139  1.570032  1.140175
min    101.000000  4.900000  1.000000
25%    102.000000  7.200000  2.000000
50%    103.000000  7.600000  2.000000
75%    104.000000  8.200000  3.000000
max    105.000000  9.100000  4.000000

In [51]:
#questions
#access information of column department
#access information of prn 103
#find out data type of each column
#perform mena,median,mode operation
#insert a new column grade
#delete gender column
#cgpa of topper
#cgpa of prn 105

In [52]:
#access information of column department
df["department"]

0           CSE
1           EEE
2          ENTC
3    MECHANICAL
4           CSE
Name: department, dtype: object

In [53]:
#access information of prn 103
df[df["roll_no"]==103]

   roll_no gender  CGPA department  Year
2      103   male   4.9       ENTC     3

In [54]:
#find out data type of each column
df.dtypes

roll_no         int64
gender         object
CGPA          float64
department     object
Year            int64
dtype: object

In [55]:
#perform mena,median,mode operation
df["CGPA"].mean()

np.float64(7.4)

In [56]:
#insert a new column grade
df["grade"]=["A","B","C","A+","B"]
df

   roll_no  gender  CGPA  department  Year grade
0      101  female   8.2         CSE     1     A
1      102    male   7.6         EEE     2     B
2      103    male   4.9        ENTC     3     C
3      104  female   9.1  MECHANICAL     4    A+
4      105    male   7.2         CSE     2     B

In [57]:
#delete gender column
df.drop("gender",axis=1)

   roll_no  CGPA  department  Year grade
0      101   8.2         CSE     1     A
1      102   7.6         EEE     2     B
2      103   4.9        ENTC     3     C
3      104   9.1  MECHANICAL     4    A+
4      105   7.2         CSE     2     B

In [58]:
#cgpa of topper
df["CGPA"].max()

9.1

In [59]:
#cgpa of prn 105
df[df["roll_no"]==105]["CGPA"]

4    7.2
Name: CGPA, dtype: float64

In [60]:
#Upload the dataset
import pandas as pd
import numpy as np
df=pd.read_csv('/content/Cars93.csv')
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [61]:
df.size

930

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Manufacturer    93 non-null     object
 1   Model           93 non-null     object
 2   Type            93 non-null     object
 3   Price           93 non-null     float64
 4   MPG.city        93 non-null     int64
 5   AirBags         59 non-null     object
 6   Horsepower      93 non-null     int64
 7   Passengers      93 non-null     int64
 8   Rear.seat.room  91 non-null     float64
 9   Luggage.room    82 non-null     float64
dtypes: float64(3), int64(3), object(4)
memory usage: 7.4+ KB

In [63]:
df.shape

(93, 10)

In [64]:
df.describe()

,Price,MPG.city,Horsepower,Passengers,Rear.seat.room,Luggage.room
count,93.000000,93.000000,93.000000,93.000000,91.000000,82.000000
mean,19.509677,22.365591,143.827957,5.086022,27.829670,13.890244
std,9.659430,5.619812,52.374410,1.038979,2.989072,2.997967
min,7.400000,15.000000,55.000000,2.000000,19.000000,6.000000
25%,12.200000,18.000000,103.000000,4.000000,26.000000,12.000000
50%,17.700000,21.000000,140.000000,5.000000,27.500000,14.000000
75%,23.300000,25.000000,170.000000,6.000000,30.000000,15.000000
max,61.900000,46.000000,300.000000,8.000000,36.000000,22.000000

In [65]:
df.tail()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [66]:
df.head()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0